### ISSUE TITLE
Crashes with helm-operator > 1.2.0

### ISSUE THREAD

**Issue by bmaehr** [hayorov/helm-gcs#131]
Hello,

We are using your plugin but it  crashes with helm-operator > 1.2.0. I'm not sure if the plugin or helm-operator needs to fix this.

https://github.com/fluxcd/helm-operator/issues/628

```
flux-helm-operator Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
flux-helm-operator goroutine 60 [running]:
flux-helm-operator k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1e57920, 0x35d0360)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x92
flux-helm-operator k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
flux-helm-operator panic(0x1e57920, 0x35d0360)
flux-helm-operator  /usr/local/go/src/runtime/panic.go:969 +0x166
flux-helm-operator k8s.io/cli-runtime/pkg/genericclioptions.(*ConfigFlags).ToRawKubeConfigLoader(0x0, 0x19f97ffd37cea9e4, 0x0)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go:136 +0x22
flux-helm-operator helm.sh/helm/v3/pkg/cli.(*EnvSettings).Namespace(0xc000634380, 0xc000535020, 0x21486ef)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/cli/environment.go:177 +0x2f
flux-helm-operator helm.sh/helm/v3/pkg/cli.(*EnvSettings).EnvVars(0xc000634380, 0x160)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/cli/environment.go:158 +0x5a1
flux-helm-operator helm.sh/helm/v3/pkg/plugin.SetupPluginEnv(0xc000634380, 0xc0004fccc0, 0x3, 0xc00015cb80, 0x2c)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/plugin/plugin.go:276 +0x40
flux-helm-operator helm.sh/helm/v3/pkg/getter.(*pluginGetter).Get(0xc000634460, 0xc00015d240, 0x3c, 0xc000534ff0, 0x5, 0x5, 0xc0003824c0, 0x40c9c4, 0xc000096320)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/getter/plugingetter.go:73 +0x290
flux-helm-operator helm.sh/helm/v3/pkg/repo.(*ChartRepository).DownloadIndexFile(0xc000096320, 0xc00053c580, 0x3, 0x4, 0xc000096320)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:128 +0x360
flux-helm-operator helm.sh/helm/v3/pkg/repo.FindChartInAuthAndTLSAndPassRepoURL(0xc000876300, 0x31, 0x0, 0x0, 0x0, 0x0, 0xc000849b35, 0xb, 0xc000849b40, 0x5, ...)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:252 +0x2dc
flux-helm-operator helm.sh/helm/v3/pkg/repo.FindChartInAuthAndTLSRepoURL(...)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:222
flux-helm-operator helm.sh/helm/v3/pkg/repo.FindChartInAuthRepoURL(0xc000876300, 0x31, 0x0, 0x0, 0x0, 0x0, 0xc000849b35, 0xb, 0xc000849b40, 0x5, ...)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:214 +0x13d
flux-helm-operator helm.sh/helm/v3/pkg/repo.FindChartInRepoURL(...)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:207
flux-helm-operator github.com/fluxcd/helm-operator/pkg/helm/v3.(*HelmV3).PullWithRepoURL(0xc00000d5c0, 0xc000876300, 0x31, 0xc000849b35, 0xb, 0xc000849b40, 0x5, 0xc00084c0a0, 0x4c, 0x0, ...)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/helm/v3/pull.go:68 +0x38c
flux-helm-operator github.com/fluxcd/helm-operator/pkg/chartsync.downloadChart(...)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/chartsync/download.go:57
flux-helm-operator github.com/fluxcd/helm-operator/pkg/chartsync.EnsureChartFetched(0x24fe860, 0xc00000d5c0, 0x212a074, 0x4, 0xc0003821c0, 0xc000534660, 0xc00078b3d8, 0x551d33, 0x246fee0, 0xc0002a4940)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/chartsync/download.go:26 +0x3c8
flux-helm-operator github.com/fluxcd/helm-operator/pkg/release.(*Release).prepareChart(0xc0005ede00, 0x24fe860, 0xc00000d5c0, 0xc00078da90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/release/release.go:161 +0x163
flux-helm-operator github.com/fluxcd/helm-operator/pkg/release.(*Release).Sync(0xc0005ede00, 0xc00078da90, 0x0, 0x0)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/release/release.go:81 +0x4a7
flux-helm-operator github.com/fluxcd/helm-operator/pkg/operator.(*Controller).syncHandler(0xc000445f20, 0xc00025fcc0, 0x1c, 0x0, 0x0)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:231 +0x5d2
flux-helm-operator github.com/fluxcd/helm-operator/pkg/operator.(*Controller).processNextWorkItem.func1(0xc000445f20, 0x1d4c920, 0xc0005326c0, 0x0, 0x0)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:185 +0xd7
flux-helm-operator github.com/fluxcd/helm-operator/pkg/operator.(*Controller).processNextWorkItem(0xc000445f20, 0x203000)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:192 +0x87
flux-helm-operator github.com/fluxcd/helm-operator/pkg/operator.(*Controller).runWorker(0xc000445f20)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:142 +0x2b
flux-helm-operator k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000f6110)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
flux-helm-operator k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0000f6110, 0x2472020, 0xc000534420, 0x7469646461222001, 0xc0005d61e0)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
flux-helm-operator k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0000f6110, 0x3b9aca00, 0x0, 0x200a7b2020202001, 0xc0005d61e0)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
flux-helm-operator k8s.io/apimachinery/pkg/util/wait.Until(0xc0000f6110, 0x3b9aca00, 0xc0005d61e0)
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
flux-helm-operator created by github.com/fluxcd/helm-operator/pkg/operator.(*Controller).Run
flux-helm-operator  /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:128 +0x188
flux-helm-operator panic: runtime error: invalid memory address or nil pointer dereference [recovered]
flux-helm-operator  panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x1893ef2] goroutine 60 [running]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105 panic(0x1e57920, 0x35d0360) /usr/local/go/src/runtime/panic.go:969 +0x166 k8s.io/cli-runtime/pkg/genericclioptions.(*ConfigFlags).ToRawKubeConfigLoader(0x0, 0x19f97ffd37cea9e4, 0x0) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go:136 +0x22 helm.sh/helm/v3/pkg/cli.(*EnvSettings).Namespace(0xc000634380, 0xc000535020, 0x21486ef) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/cli/environment.go:177 +0x2f helm.sh/helm/v3/pkg/cli.(*EnvSettings).EnvVars(0xc000634380, 0x160) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/cli/environment.go:158 +0x5a1 helm.sh/helm/v3/pkg/plugin.SetupPluginEnv(0xc000634380, 0xc0004fccc0, 0x3, 0xc00015cb80, 0x2c) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/plugin/plugin.go:276 +0x40 helm.sh/helm/v3/pkg/getter.(*pluginGetter).Get(0xc000634460, 0xc00015d240, 0x3c, 0xc000534ff0, 0x5, 0x5, 0xc0003824c0, 0x40c9c4, 0xc000096320) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/getter/plugingetter.go:73 +0x290 helm.sh/helm/v3/pkg/repo.(*ChartRepository).DownloadIndexFile(0xc000096320, 0xc00053c580, 0x3, 0x4, 0xc000096320) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:128 +0x360 helm.sh/helm/v3/pkg/repo.FindChartInAuthAndTLSAndPassRepoURL(0xc000876300, 0x31, 0x0, 0x0, 0x0, 0x0, 0xc000849b35, 0xb, 0xc000849b40, 0x5, ...) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:252 +0x2dc helm.sh/helm/v3/pkg/repo.FindChartInAuthAndTLSRepoURL(...) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:222 helm.sh/helm/v3/pkg/repo.FindChartInAuthRepoURL(0xc000876300, 0x31, 0x0, 0x0, 0x0, 0x0, 0xc000849b35, 0xb, 0xc000849b40, 0x5, ...) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:214 +0x13d helm.sh/helm/v3/pkg/repo.FindChartInRepoURL(...) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go:207 github.com/fluxcd/helm-operator/pkg/helm/v3.(*HelmV3).PullWithRepoURL(0xc00000d5c0, 0xc000876300, 0x31, 0xc000849b35, 0xb, 0xc000849b40, 0x5, 0xc00084c0a0, 0x4c, 0x0, ...) /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/helm/v3/pull.go:68 +0x38c github.com/fluxcd/helm-operator/pkg/chartsync.downloadChart(...) /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/chartsync/download.go:57 github.com/fluxcd/helm-operator/pkg/chartsync.EnsureChartFetched(0x24fe860, 0xc00000d5c0, 0x212a074, 0x4, 0xc0003821c0, 0xc000534660, 0xc00078b3d8, 0x551d33, 0x246fee0, 0xc0002a4940) /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/chartsync/download.go:26 +0x3c8 github.com/fluxcd/helm-operator/pkg/release.(*Release).prepareChart(0xc0005ede00, 0x24fe860, 0xc00000d5c0, 0xc00078da90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/release/release.go:161 +0x163 github.com/fluxcd/helm-operator/pkg/release.(*Release).Sync(0xc0005ede00, 0xc00078da90, 0x0, 0x0) /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/release/release.go:81 +0x4a7 github.com/fluxcd/helm-operator/pkg/operator.(*Controller).syncHandler(0xc000445f20, 0xc00025fcc0, 0x1c, 0x0, 0x0) /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:231 +0x5d2 github.com/fluxcd/helm-operator/pkg/operator.(*Controller).processNextWorkItem.func1(0xc000445f20, 0x1d4c920, 0xc0005326c0, 0x0, 0x0) /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:185 +0xd7 github.com/fluxcd/helm-operator/pkg/operator.(*Controller).processNextWorkItem(0xc000445f20, 0x203000) /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:192 +0x87 github.com/fluxcd/helm-operator/pkg/operator.(*Controller).runWorker(0xc000445f20) /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:142 +0x2b k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000f6110) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0000f6110, 0x2472020, 0xc000534420, 0x7469646461222001, 0xc0005d61e0) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3 k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0000f6110, 0x3b9aca00, 0x0, 0x200a7b2020202001, 0xc0005d61e0) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98 k8s.io/apimachinery/pkg/util/wait.Until(0xc0000f6110, 0x3b9aca00, 0xc0005d61e0) /home/circleci/go/src/github.com/fluxcd/helm-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d created by github.com/fluxcd/helm-operator/pkg/operator.(*Controller).Run /home/circleci/go/src/github.com/fluxcd/helm-operator/pkg/operator/operator.go:128 +0x188

```

**Comment by hayorov** [comment]
It seems that the problem was introduced in helm-operator > 1.2.0+ help plugins subsystem, ref https://github.com/fluxcd/helm-operator/issues/628 probably something wrong with env setup (partially fixed here https://github.com/fluxcd/helm-operator/pull/626)

Unfortunately, there is nothing that we can do in `helm-gcs`, `help-operator` panic during the worker setup for help-plugin and it's a generic part (not specific to `helm-gcs`).
